Directory: ./sample11
Test Output:
============================= test session starts ==============================
platform darwin -- Python 3.10.12, pytest-7.4.0, pluggy-1.3.0
rootdir: /Users/DELL/Desktop/new_chatgpt/cat3_classes
plugins: dash-2.14.0
collected 0 items / 1 error

==================================== ERRORS ====================================
__________________ ERROR collecting sample11/test_example.py ___________________
ImportError while importing test module '/Users/DELL/Desktop/new_chatgpt/cat3_classes/sample11/test_example.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../opt/anaconda3/envs/pyng310/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
sample11/test_example.py:3: in <module>
    from example import HTTPieCertificate, HTTPieHTTPSAdapter, SSL_VERSION_ARG_MAPPING, AVAILABLE_SSL_VERSION_ARG_MAPPING
sample11/example.py:4: in <module>
    from adapters import HTTPAdapter
E   ModuleNotFoundError: No module named 'adapters'
=========================== short test summary info ============================
ERROR sample11/test_example.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.11s ===============================

Test Error Output:


